# Generated by Django 4.2.5 on 2023-10-04 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_picture', models.ImageField(blank=True, null=True, upload_to='product_pictures/')),
                ('product_name', models.CharField(max_length=255)),
                ('post_description', models.CharField(max_length=255)),
                ('total_likes', models.IntegerField(blank=True, null=True)),
                ('total_favorites', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
