# Generated by Django 4.2.5 on 2023-10-09 07:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0007_rename_product_category_productcategory_category_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_picture', models.ImageField(blank=True, null=True, upload_to='product_pictures/')),
                ('post_description', models.CharField(max_length=255)),
                ('total_likes', models.IntegerField(blank=True, null=True)),
                ('total_favorites', models.IntegerField(blank=True, null=True)),
                ('datetimePublished', models.DateTimeField(verbose_name='Datetime Published')),
                ('postUser', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='products.users')),
            ],
        ),
    ]
