# Generated by Django 4.2.5 on 2023-10-11 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_posts_datetimepublished'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='is_shown',
            field=models.BooleanField(default=True),
        ),
    ]
