# Generated by Django 4.2.5 on 2023-10-20 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_posts_post_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='post_picture',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
