# Generated by Django 4.2.3 on 2023-10-25 19:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0005_alter_posts_post_picture"),
    ]

    operations = [
        migrations.AddField(
            model_name="posts",
            name="total_dislikes",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name="posts",
            name="total_likes",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
