# Generated by Django 4.2.5 on 2023-11-06 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_posts_total_dislikes_alter_posts_total_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='is_disliked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='posts',
            name='is_favorite',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='posts',
            name='is_liked',
            field=models.BooleanField(default=False),
        ),
    ]
