# Generated by Django 4.2.5 on 2023-11-07 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='datetimePublished',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='posts',
            name='datetimePublished',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
