# Generated by Django 4.2.5 on 2023-11-07 08:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_remove_users_iscurrentuser_users_bio_and_more'),
        ('main', '0010_alter_comments_datetimepublished_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='postUser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.users'),
        ),
    ]
