# Generated by Django 4.2.5 on 2023-11-07 08:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_remove_users_iscurrentuser_users_bio_and_more'),
        ('main', '0011_alter_posts_postuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='commentUser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.users'),
        ),
        migrations.AlterField(
            model_name='comments',
            name='comment_replies',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.comments'),
        ),
        migrations.AlterField(
            model_name='comments',
            name='postId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.posts'),
        ),
        migrations.AlterField(
            model_name='interaction',
            name='post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.posts'),
        ),
        migrations.AlterField(
            model_name='interaction',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.users'),
        ),
    ]
