# Generated by Django 4.2.5 on 2023-11-07 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_comments_commentuser_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='postId',
            new_name='post',
        ),
    ]
