# Generated by Django 4.2.5 on 2023-11-07 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_rename_postid_comments_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='commentUser',
            new_name='comment_user',
        ),
        migrations.RenameField(
            model_name='comments',
            old_name='datetimePublished',
            new_name='datetime_published',
        ),
        migrations.RenameField(
            model_name='posts',
            old_name='datetimePublished',
            new_name='datetime_published',
        ),
        migrations.RenameField(
            model_name='posts',
            old_name='postUser',
            new_name='post_user',
        ),
    ]
