# Generated by Django 4.2.5 on 2023-11-21 05:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_rename_commentuser_comments_comment_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='comment_replies',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='main.comments'),
        ),
        migrations.AlterField(
            model_name='comments',
            name='post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='main.posts'),
        ),
    ]
