# Generated by Django 4.2.5 on 2023-09-21 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='isCurrentUser',
            field=models.BooleanField(default=False),
        ),
    ]
