# Generated by Django 4.2.5 on 2023-10-04 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcategory',
            name='category_icon',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
