# Generated by Django 4.2.5 on 2023-10-04 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_productcategory_category_icon'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Products',
            new_name='Product',
        ),
    ]
