# Generated by Django 4.2.5 on 2023-10-08 12:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_rename_products_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productcategory',
            old_name='product_category',
            new_name='category_name',
        ),
        migrations.AddField(
            model_name='product',
            name='product_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='products.productcategory'),
        ),
    ]
