# Generated by Django 4.2.5 on 2023-12-08 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_alter_comments_comment_user_alter_interaction_user_and_more'),
        ('products', '0010_users_type'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Users',
        ),
    ]
